// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjkrjjhsghdxowhdojxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqa3JqamhzZ2hkeG93aGRvanhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDAwNDAsImV4cCI6MjA3MDkxNjA0MH0.oWpY1O_Fc3wFCy8KIzyqLd1ge098kuMMaJcdq3yIWbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});